// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.domain;

<<<<<<< HEAD
import es.uca.iw.domain.Cv;
import es.uca.iw.domain.Empresa;
import es.uca.iw.domain.Usuario;
import es.uca.iw.reference.Sexo;
import es.uca.iw.reference.TipoUsuario;
=======
import es.uca.iw.domain.Curriculum;
import es.uca.iw.domain.Usuario;
import es.uca.iw.reference.Sexo;
>>>>>>> 6cfd50639538555ce28e1e7bf8ef397311f4aa3a
import java.util.Date;
import java.util.Set;

privileged aspect Usuario_Roo_JavaBean {
    
    public String Usuario.getNombre() {
        return this.nombre;
    }
    
    public void Usuario.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public String Usuario.getApellidos() {
        return this.apellidos;
    }
    
    public void Usuario.setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    public String Usuario.getEmail() {
        return this.email;
    }
    
    public void Usuario.setEmail(String email) {
        this.email = email;
    }
    
<<<<<<< HEAD
    public String Usuario.getDni() {
        return this.dni;
    }
    
    public void Usuario.setDni(String dni) {
        this.dni = dni;
    }
    
=======
>>>>>>> 6cfd50639538555ce28e1e7bf8ef397311f4aa3a
    public String Usuario.getContrasena() {
        return this.contrasena;
    }
    
    public void Usuario.setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    
    public Date Usuario.getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void Usuario.setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
    public String Usuario.getDireccion() {
        return this.direccion;
    }
    
    public void Usuario.setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    public Integer Usuario.getTelefono() {
        return this.telefono;
    }
    
    public void Usuario.setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    
<<<<<<< HEAD
    public TipoUsuario Usuario.getTipo() {
        return this.tipo;
    }
    
    public void Usuario.setTipo(TipoUsuario tipo) {
        this.tipo = tipo;
    }
    
=======
>>>>>>> 6cfd50639538555ce28e1e7bf8ef397311f4aa3a
    public Sexo Usuario.getSexo() {
        return this.sexo;
    }
    
    public void Usuario.setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
    
<<<<<<< HEAD
    public Set<Empresa> Usuario.getEmpresas_gestionadas() {
        return this.empresas_gestionadas;
    }
    
    public void Usuario.setEmpresas_gestionadas(Set<Empresa> empresas_gestionadas) {
        this.empresas_gestionadas = empresas_gestionadas;
    }
    
    public Set<Cv> Usuario.getCvs() {
        return this.cvs;
    }
    
    public void Usuario.setCvs(Set<Cv> cvs) {
        this.cvs = cvs;
=======
    public String Usuario.getDni() {
        return this.dni;
    }
    
    public void Usuario.setDni(String dni) {
        this.dni = dni;
    }
    
    public Set<Curriculum> Usuario.getCurriculums() {
        return this.curriculums;
    }
    
    public void Usuario.setCurriculums(Set<Curriculum> curriculums) {
        this.curriculums = curriculums;
    }
    
    public Boolean Usuario.getIs_demandante() {
        return this.is_demandante;
    }
    
    public void Usuario.setIs_demandante(Boolean is_demandante) {
        this.is_demandante = is_demandante;
    }
    
    public Boolean Usuario.getIs_gestor_ett() {
        return this.is_gestor_ett;
    }
    
    public void Usuario.setIs_gestor_ett(Boolean is_gestor_ett) {
        this.is_gestor_ett = is_gestor_ett;
    }
    
    public Boolean Usuario.getIs_gestor_empresa() {
        return this.is_gestor_empresa;
    }
    
    public void Usuario.setIs_gestor_empresa(Boolean is_gestor_empresa) {
        this.is_gestor_empresa = is_gestor_empresa;
    }
    
    public Boolean Usuario.getIs_administrador() {
        return this.is_administrador;
    }
    
    public void Usuario.setIs_administrador(Boolean is_administrador) {
        this.is_administrador = is_administrador;
    }
    
    public Boolean Usuario.getIs_superadministrador() {
        return this.is_superadministrador;
    }
    
    public void Usuario.setIs_superadministrador(Boolean is_superadministrador) {
        this.is_superadministrador = is_superadministrador;
>>>>>>> 6cfd50639538555ce28e1e7bf8ef397311f4aa3a
    }
    
}
